/**
 * RunSubsystem — host object mounted at runtime.runners.
 *
 * Implements the Run role from blur-agent/library/architecture/role-run.md.
 * A Runner is a stable record of work; the bridge session is its current
 * implementation. The Runner identity persists across session compaction,
 * end, or replacement — sessions are an implementation detail.
 *
 * v0.1 SCOPE:
 *   - Record-based subsystem; in-memory map + Persistable JSON snapshot
 *   - file / get / list / bind / markCompleted / markFailed / setTranscript
 *   - takeaways for context injection
 *   - NO actual bridge spawn — that's a future integration. Today the
 *     Runner gets manually bound to an existing bridge session via bind().
 *     Bootstrap: human/UI starts a Claude session, then calls bind() to
 *     associate it with a filed Runner.
 *   - Audit events emit for every lifecycle transition.
 */

import * as crypto from 'crypto';

import type { BlurAIRuntime, Persistable } from 'blur-ai-runtime';

const SCHEMA_VERSION = 1;

export type RunnerStatus = 'queued' | 'running' | 'paused' | 'completed' | 'failed';
export type RunnerScope = 'runtime' | 'project' | 'pack' | 'track';

export interface RunnerRef {
  kind: string;
  ref: string;
}

export interface Runner {
  id: string;
  title: string;
  briefSlug?: string;        // the Brief defining this Runner's work
  prompt?: string;           // prompt seed (may be generated by Conductor)
  status: RunnerStatus;
  bridgeSessionId?: string;  // current implementation handle
  transcript?: string;       // copied snapshot (filled by Secretary)
  forRef?: RunnerRef;        // what this Runner is operating on (project, ticket, etc.)
  filedAt: string;
  filedBy: string;
  startedAt?: string;
  completedAt?: string;
  outcome?: string;
  failureReason?: string;
  scope: RunnerScope;
  tags?: string[];
}

export type RunnerSummary = Omit<Runner, 'transcript' | 'prompt'>;

interface Snapshot {
  schemaVersion: number;
  runners: Runner[];
}

export interface FileRunnerOpts {
  title: string;
  briefSlug?: string;
  prompt?: string;
  forRef?: RunnerRef;
  filedBy: string;
  scope?: RunnerScope;
  tags?: string[];
}

export interface ListRunnersOpts {
  status?: RunnerStatus | RunnerStatus[] | 'all';
  scope?: RunnerScope;
  forRef?: RunnerRef;
  limit?: number;
}

export interface BindRunnerOpts {
  bridgeSessionId: string;
}

export interface CompleteRunnerOpts {
  outcome?: string;
  transcript?: string;
  by?: string;
}

export interface FailRunnerOpts {
  reason: string;
  by?: string;
}

export interface TakeawaysOpts {
  scope?: RunnerScope;
  format?: 'list' | 'prose';
}

export class RunSubsystem implements Persistable {
  private readonly byId = new Map<string, Runner>();
  private runtime: BlurAIRuntime | null = null;
  private _dirty = false;

  attachRuntime(runtime: BlurAIRuntime): void { this.runtime = runtime; }

  saveJson(): string {
    return JSON.stringify({
      schemaVersion: SCHEMA_VERSION,
      runners: [...this.byId.values()],
    } as Snapshot);
  }

  loadJson(s: string): void {
    if (!s) return;
    let data: Partial<Snapshot>;
    try { data = JSON.parse(s) as Partial<Snapshot>; } catch { return; }
    if (data.schemaVersion !== SCHEMA_VERSION) return;
    this.byId.clear();
    for (const r of data.runners ?? []) if (r?.id) this.byId.set(r.id, r);
    this._dirty = false;
  }

  consumeDirty(): boolean {
    const d = this._dirty;
    this._dirty = false;
    return d;
  }

  // ---------- Mutations ----------

  file(opts: FileRunnerOpts): Runner {
    if (!opts.title) throw new Error('file: title required');
    if (!opts.filedBy) throw new Error('file: filedBy required');
    const id = 'rnr_' + crypto.randomUUID().replace(/-/g, '').slice(0, 12);
    const runner: Runner = {
      id,
      title: opts.title,
      briefSlug: opts.briefSlug,
      prompt: opts.prompt,
      forRef: opts.forRef,
      filedAt: new Date().toISOString(),
      filedBy: opts.filedBy,
      status: 'queued',
      scope: opts.scope ?? 'runtime',
      tags: opts.tags,
    };
    this.byId.set(id, runner);
    this._dirty = true;
    this.emit('runners.filed', { id, title: opts.title, briefSlug: opts.briefSlug, by: opts.filedBy });
    return runner;
  }

  bind(id: string, opts: BindRunnerOpts): Runner {
    const r = this.require(id);
    if (r.status !== 'queued' && r.status !== 'paused') {
      throw new Error(`bind: runner ${id} is in status ${r.status}; only queued/paused can bind`);
    }
    const next: Runner = {
      ...r,
      status: 'running',
      bridgeSessionId: opts.bridgeSessionId,
      startedAt: r.startedAt ?? new Date().toISOString(),
    };
    this.byId.set(id, next);
    this._dirty = true;
    this.emit('runners.bound', { id, bridgeSessionId: opts.bridgeSessionId });
    return next;
  }

  pause(id: string): Runner {
    const r = this.require(id);
    if (r.status !== 'running') {
      throw new Error(`pause: runner ${id} is in status ${r.status}; only running can pause`);
    }
    const next: Runner = { ...r, status: 'paused' };
    this.byId.set(id, next);
    this._dirty = true;
    this.emit('runners.paused', { id });
    return next;
  }

  markCompleted(id: string, opts: CompleteRunnerOpts = {}): Runner {
    const r = this.require(id);
    if (r.status === 'completed' || r.status === 'failed') {
      throw new Error(`markCompleted: runner ${id} is already ${r.status}`);
    }
    const next: Runner = {
      ...r,
      status: 'completed',
      completedAt: new Date().toISOString(),
      outcome: opts.outcome,
      transcript: opts.transcript ?? r.transcript,
    };
    this.byId.set(id, next);
    this._dirty = true;
    this.emit('runners.completed', { id, outcome: opts.outcome ?? null, by: opts.by ?? null });
    return next;
  }

  markFailed(id: string, opts: FailRunnerOpts): Runner {
    const r = this.require(id);
    if (r.status === 'completed' || r.status === 'failed') {
      throw new Error(`markFailed: runner ${id} is already ${r.status}`);
    }
    const next: Runner = {
      ...r,
      status: 'failed',
      completedAt: new Date().toISOString(),
      failureReason: opts.reason,
    };
    this.byId.set(id, next);
    this._dirty = true;
    this.emit('runners.failed', { id, reason: opts.reason, by: opts.by ?? null });
    return next;
  }

  /** Used by Secretary to attach a transcript snapshot. */
  setTranscript(id: string, transcript: string): Runner {
    const r = this.require(id);
    const next: Runner = { ...r, transcript };
    this.byId.set(id, next);
    this._dirty = true;
    this.emit('runners.transcript-synced', { id, length: transcript.length });
    return next;
  }

  // ---------- Reads ----------

  get(id: string): Runner | null { return this.byId.get(id) ?? null; }

  list(opts: ListRunnersOpts = {}): RunnerSummary[] {
    const statusFilter = normalizeStatus(opts.status);
    const limit = opts.limit ?? Infinity;
    const out: Runner[] = [];
    for (const r of this.byId.values()) {
      if (statusFilter !== 'all' && !statusFilter.includes(r.status)) continue;
      if (opts.scope && r.scope !== opts.scope) continue;
      if (opts.forRef) {
        if (!r.forRef
          || r.forRef.kind !== opts.forRef.kind
          || r.forRef.ref !== opts.forRef.ref) continue;
      }
      out.push(r);
    }
    out.sort((a, b) => {
      const sa = statusOrder(a.status);
      const sb = statusOrder(b.status);
      if (sa !== sb) return sa - sb;
      return a.filedAt.localeCompare(b.filedAt);
    });
    return out.slice(0, limit).map(stripBig);
  }

  /** Flat takeaways — active and queued Runners, for context injection. */
  takeaways(opts: TakeawaysOpts = {}): string {
    const active = this.list({
      scope: opts.scope,
      status: ['running', 'queued', 'paused'],
    });
    if (active.length === 0) {
      return `(no active Runners${opts.scope ? ` in scope=${opts.scope}` : ''})`;
    }
    const blocks = active.map(r => `[${r.status}] ${r.title} (${r.id})`);
    if (opts.format === 'prose') return blocks.join('; ');
    const head = `Runners in flight${opts.scope ? ` in scope=${opts.scope}` : ''}:`;
    return [head, '', ...blocks.map((s, i) => `${i + 1}. ${s}`)].join('\n');
  }

  // ---------- Internals ----------

  private require(id: string): Runner {
    const r = this.byId.get(id);
    if (!r) throw new Error(`runner not found: ${id}`);
    return r;
  }

  private emit(kind: string, data: Record<string, unknown>): void {
    if (!this.runtime) return;
    try {
      const audit = (this.runtime as unknown as { audit?: { emit?: (e: unknown) => void } }).audit;
      audit?.emit?.({ kind, data });
    } catch (err) {
      console.warn(`[runners] audit emit failed for ${kind}:`, (err as Error).message);
    }
  }
}

function stripBig(r: Runner): RunnerSummary {
  const { transcript: _t, prompt: _p, ...rest } = r;
  return rest;
}

function statusOrder(s: RunnerStatus): number {
  switch (s) {
    case 'running': return 0;
    case 'queued': return 1;
    case 'paused': return 2;
    case 'completed': return 3;
    case 'failed': return 4;
  }
}

function normalizeStatus(s: ListRunnersOpts['status']): RunnerStatus[] | 'all' {
  if (s === 'all') return 'all';
  if (!s) return ['queued', 'running', 'paused'];
  if (Array.isArray(s)) return s;
  return [s];
}
